### ISSUE TITLE
Fix passage text position

### ISSUE THREAD

**Issue by johnraftery** [johnraftery/BibleTrainer#21]
I'm sorry. I broke it :(

Needed to put the passage in a div in order to pick up the swipe events:
https://stackoverflow.com/questions/45574491/ionic-swipe-gesture-not-working-on-phone

**Comment by jamesdoc** [comment]
Not sure what text position is broken here… I've pulled on master...

**Comment by johnraftery** [comment]
![image](https://user-images.githubusercontent.com/44305598/51199206-1a0f3c80-18ee-11e9-90fc-612d43ab08ec.png)

Looks like the spacing at the top and sides of the screen has gone awry.

**Comment by jamesdoc** [comment]
Resolved in https://github.com/johnraftery/BibleTrainer/commit/134b3cb800667695011eee2b4dbd19cd8641ba97
