### ISSUE TITLE
Indented lines of text

### ISSUE THREAD

**Issue by johnraftery** [johnraftery/BibleTrainer#25]
Make the whole line indented, so that if the text is long enough to wrap, the overflow part of the text is also indented. Could be something similar to the replaceVerseMarker method - wrapping the line in a span with it's own css.

**Comment by jamesdoc** [comment]
Which do you mean? First or second in this example?
http://jsfiddle.net/ryNJk/

**Comment by johnraftery** [comment]
Ah, seeing your demo on a desktop makes sense. To be honest, it's neither of these. Did my message make sense?
Blessed is the man
[Indent]who walks not in
[Indent]the council of the
[Indent]wicked
nor stands in the
way of sinners,
[Indent]nor sits in the
[Indent]seat of scoffers

So if a line is indented (in the original text), the whole line should be indented, even if it wraps.

**Comment by johnraftery** [comment]
![image](https://user-images.githubusercontent.com/44305598/51244591-6190d980-197d-11e9-811a-c47e32ebe384.png)

**Comment by johnraftery** [comment]
![indentation](https://user-images.githubusercontent.com/44305598/51244661-85541f80-197d-11e9-8624-dca7262ff645.png)

**Comment by jamesdoc** [comment]
Let me know what you think of this ☝️
