### ISSUE TITLE
Listen to audio

### ISSUE THREAD

**Issue by johnraftery** [johnraftery/BibleTrainer#28]

**Comment by jamesdoc** [comment]
I've got this working. However I want to fix up how the UI works here to include play/pause etc before adding to master.

**Comment by johnraftery** [comment]
Cool!!

I think since we have swiping between passages now, we can remove previous and next passage buttons.

So, from left-to-right, it could be: listen/stop, hide section, next section (in the FAB), next verse, recite.

Thoughts?

**Comment by jamesdoc** [comment]
<img width="506" alt="screenshot 2019-01-16 at 10 43 50" src="https://user-images.githubusercontent.com/790343/51243899-a3b91b80-197b-11e9-8321-dae7f4a95b2f.PNG">

I'm wondering if this is a good and happy place to aim for…

- We make the FAB action customisable in the settings - show by phrase or by verse. This means that we don't need the additional verse reveal button
- The undo button is still visible
- the next/previous passage function is hidden into the swipe functionality
- Recite sits next to the previous button
- Play audio sits up top

**Comment by johnraftery** [comment]
Oooooooo, I like it!

**Comment by jamesdoc** [comment]
Shiny. It also closer matches the material UI guidelines too: https://material.io/design/components/app-bars-bottom.html#behavior

**Comment by jamesdoc** [comment]
Just FYI… I'm not planning to implement to kebab (bottom-right) yet… it's just a place for a couple of other ideas that I've got sitting in my head…

**Comment by jamesdoc** [comment]
Right… I'm going to squash this down into one nice commit and then we can both code review it before merging into master.

**Comment by johnraftery** [comment]
Sounds good. Will you include my thing on the network checking?

**Comment by jamesdoc** [comment]
Not here… It's a different optimisation work which we'll want to pull into something more holistic.
