### ISSUE TITLE
Global 'hasInternet' flag

### ISSUE THREAD

**Issue by jamesdoc** [johnraftery/BibleTrainer#30]
We need a flag that is accessible though the whole app which knows if there is a network connection.

- We cannot add new scripture to the app without it a network connection (unless we locally cache the the thing…)
- We cannot request the mp3 without it

If we can't do these things, the buttons should not appear in the UI (or at least be disabled with a message).

John, could you implement in a branch please?

**Comment by johnraftery** [comment]
Have done this in a new branch created from the ListenToAudio branch. If ok with you, feel free to merge back into ListenToAudio.

**Comment by johnraftery** [comment]
Have done this in a new branch made from ListenToAudio. If you're happy, feel free to merge it back into ListenToAudio.
