### ISSUE TITLE
Move the add-passage FAB button, make more prominent.

### ISSUE THREAD

**Issue by johnraftery** [johnraftery/BibleTrainer#43]
![idea](https://user-images.githubusercontent.com/44305598/52483716-7d6a5280-2bac-11e9-957d-9fc85161f457.png)

**Comment by jamesdoc** [comment]
Agree that this is an issue, not sure that moving the FAB is the answer. Will mull.

**Comment by jamesdoc** [comment]
I think that this will be resolved by adding in a better empty state screen which is here: https://github.com/johnraftery/BibleTrainer/issues/14
