### ISSUE TITLE
Credit line for ESV

### ISSUE THREAD

**Issue by jamesdoc** [johnraftery/BibleTrainer#8]
Credit line should read:

> Scripture quotations marked “ESV” are from the ESV® Bible (The Holy Bible, English Standard Version®), copyright © 2001 by Crossway, a publishing ministry of Good News Publishers. Used by permission. All rights reserved. You may not copy or download more than 500 consecutive verses of the ESV Bible or more than one half of any book of the ESV Bible.

**Comment by johnraftery** [comment]
Could put this copyright at the bottom of the add passage screen? And put "ESV" at the end of the reference part of the recite passage titlebar?

**Comment by jamesdoc** [comment]
It could… but it is HUGE. I'll do some design work for it and ask you to implement (nothing major, probably an alert for now…)

**Comment by jamesdoc** [comment]
@johnraftery Could you implement the functionality something like this? I'll fix up the styling later…

<img width="1050" alt="screenshot 2018-12-20 at 12 16 20" src="https://user-images.githubusercontent.com/790343/50284511-17393d00-0451-11e9-8ee9-c0e9e4b28b8a.PNG">

The footer text will always be there, the last line to be added always has a bottom margin of `alot` 👈  to be determined.

When clicking the 'find out more' you get a nice happy dialogue box…

How does that sound?
